//! Canonical ForgeGUI consumer facade.
#![forbid(unsafe_code)]
pub use egui;
pub use forge_gui_browser as browser;
pub use forge_gui_canvas as canvas;
pub use forge_gui_canvas::*;
pub use forge_gui_chrome as chrome;
pub use forge_gui_command as command;
pub use forge_gui_console as console;
pub use forge_gui_console::*;
pub use forge_gui_core as core;
pub use forge_gui_core::*;
pub use forge_gui_egui as egui_backend;
pub use forge_gui_egui::*;
pub use forge_gui_icons as icons;
pub use forge_gui_icons::*;
pub use forge_gui_inspector as inspector;
pub use forge_gui_layout as layout;
pub use forge_gui_notify as notify;
pub use forge_gui_notify::*;
pub use forge_gui_panels as panels;
pub use forge_gui_pie as pie;
pub use forge_gui_pie::*;
pub use forge_gui_rails as rails;
pub use forge_gui_shell as shell;
pub use forge_gui_shell::*;
pub use forge_gui_theme as theme;
pub use forge_gui_widgets as widgets;
pub use forge_gui_workspace as workspace;
pub use forge_render_surface as render_surface;
